# Generated by Django 4.1.3 on 2022-11-14 15:51

import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.files.models.pdf_publication_upload_to)),
                ('isPDF', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Publication PDF',
                'verbose_name_plural': 'Publication PDF',
            },
        ),
    ]
