# Generated by Django 4.1.3 on 2022-11-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpdf',
            name='reffield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_publication', to='publications.publication'),
        ),
    ]
