# Generated by Django 4.1.3 on 2022-11-16 05:14

import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonCVPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.files.models.pdf_person_cv_upload_to)),
                ('isPDF', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Person CV PDF',
                'verbose_name_plural': 'Person CV PDF',
            },
        ),
    ]
