# Generated by Django 4.1.3 on 2022-11-16 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_personcvpdf'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personcvpdf',
            name='reffield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_personCV', to='people.person'),
        ),
    ]
