# Generated by Django 4.1.3 on 2022-11-13 20:40

import apps.images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverResearchField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.images.models.research_cover_upload_to)),
                ('isCover', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImageResearchField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.images.models.research_images_upload_to)),
            ],
        ),
    ]
