# Generated by Django 4.1.3 on 2022-11-13 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageresearchfield',
            name='reffield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_research', to='research.researchfield'),
        ),
        migrations.AddField(
            model_name='coverresearchfield',
            name='reffield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_research', to='research.researchfield'),
        ),
    ]
