# Generated by Django 4.1.3 on 2022-11-15 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('images', '0003_covernews_imagenews'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenews',
            name='reffield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_news', to='news.news'),
        ),
        migrations.AddField(
            model_name='covernews',
            name='reffield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_news', to='news.news'),
        ),
    ]
