# Generated by Django 4.1.3 on 2022-11-16 05:14

import apps.images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_imagenews_reffield_covernews_reffield'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.images.models.person_cover_upload_to)),
                ('isCover', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.images.models.person_images_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='PicProfilePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.images.models.person_pic_upload_to)),
                ('isPic', models.BooleanField(default=False)),
            ],
        ),
    ]
