# Generated by Django 4.1.3 on 2022-11-16 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('images', '0005_coverperson_imageperson_picprofileperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='picprofileperson',
            name='reffield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pic_person', to='people.person'),
        ),
        migrations.AddField(
            model_name='imageperson',
            name='reffield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_person', to='people.person'),
        ),
        migrations.AddField(
            model_name='coverperson',
            name='reffield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_person', to='people.person'),
        ),
    ]
