# Generated by Django 4.1.3 on 2022-11-16 11:39

import apps.images.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
        ('images', '0006_picprofileperson_reffield_imageperson_reffield_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.images.models.carousel_upload_to)),
                ('isCover', models.BooleanField(default=False)),
                ('reffield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_carousel', to='carousel.carousel')),
            ],
        ),
    ]
