# Generated by Django 4.1.3 on 2022-11-21 06:07

import apps.images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_covercarousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.images.models.tool_upload_to)),
                ('isCover', models.BooleanField(default=False)),
            ],
        ),
    ]
