# Generated by Django 4.1.3 on 2022-11-21 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
        ('images', '0008_covertool'),
    ]

    operations = [
        migrations.AddField(
            model_name='covertool',
            name='reffield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_tool', to='tools.tool'),
        ),
    ]
