# Generated by Django 4.1.3 on 2022-11-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        ('crossuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('authors', models.CharField(max_length=255)),
                ('magazine', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('doi', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('bibtex', models.TextField(blank=True, null=True)),
                ('corresponding', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_publication', to='crossuser.userid')),
                ('author_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_publication_update', to='crossuser.userid')),
                ('field', models.ManyToManyField(blank=True, to='research.researchfield')),
            ],
        ),
    ]
