# Generated by Django 4.1.3 on 2022-11-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='link_scholar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
